source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.2'
use_frameworks!
target 'SmarterOffice' do
  pod 'Starscream', '~> 1.1.3'
  pod 'Charts', '~> 2.2.4'
  pod 'KDCircularProgress', '~>1.4.0'
  pod 'SwiftyJSON', '~>2.3.2'
end
