source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.2'
use_frameworks!
target 'SmarterOffice' do
  pod 'Starscream', '~> 1.1.1'
  pod 'Charts', '~> 2.2.3'
  pod 'KDCircularProgress'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
